// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models.EFModels;

public partial class AppDbContext : DbContext
{
    public AppDbContext()
    {
    }

    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<NetBankUser> NetBankUsers { get; set; }

//    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
//#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
//        => optionsBuilder.UseSqlServer("Data Source=(localdb)\\MSSQLLocalDB;Initial Catalog=Bank;Integrated Security=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Account>(entity =>
        {
            entity.HasKey(e => e.AccountGuid).HasName("PK__Accounts__B6B6EBEDA40E15E8");

            entity.Property(e => e.AccountGuid).IsFixedLength();
            entity.Property(e => e.OwnerGuid).IsFixedLength();

            entity.HasOne(d => d.Owner).WithMany(p => p.Accounts).HasConstraintName("FK__Accounts__OwnerG__267ABA7A");
        });

        modelBuilder.Entity<NetBankUser>(entity =>
        {
            entity.HasKey(e => e.UserGuid).HasName("PK__NetBankU__99B7F23A6BA18421");

            entity.Property(e => e.UserGuid).IsFixedLength();
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}