// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models.EFModels;

public partial class NetBankUser
{
    [Key]
    [StringLength(36)]
    [Unicode(false)]
    public string UserGuid { get; set; }

    [Column("NationalID")]
    [StringLength(10)]
    [Unicode(false)]
    public string NationalId { get; set; }

    public int? UserKind { get; set; }

    [StringLength(50)]
    public string UserName { get; set; }

    [StringLength(10)]
    [Unicode(false)]
    public string Status { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string ApplyDate { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string CacheTime { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string UpdatePasswordDate { get; set; }

    public bool? IsAlive { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string SyncAccount { get; set; }

    [InverseProperty("Owner")]
    public virtual ICollection<Account> Accounts { get; set; } = new List<Account>();
}